services:
  - type: web
    name: farmacarex
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin-allow-popups
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: require-corp
